In [8]:
import numpy as np

In [9]:
my_data = np.genfromtxt('/sales_fact_1997_8.csv', delimiter=',')

In [10]:
print(my_data)

[[       nan        nan        nan ...        nan        nan        nan]
 [3.3700e+02 3.7100e+02 6.2800e+03 ... 1.5000e+00 5.1000e-01 2.0000e+00]
 [1.5120e+03 3.7100e+02 6.2800e+03 ... 1.6200e+00 6.3180e-01 3.0000e+00]
 ...
 [2.1600e+02 1.0360e+03 9.3940e+03 ... 1.0800e+01 5.2920e+00 3.0000e+00]
 [3.2600e+02 1.0360e+03 9.3940e+03 ... 9.8800e+00 4.3472e+00 4.0000e+00]
 [4.1000e+02 1.0360e+03 9.3940e+03 ... 5.0400e+00 2.3184e+00 4.0000e+00]]


In [11]:
np.savetxt("ruhaha.csv", my_data, delimiter=",")

In [15]:
my_data = my_data[my_data[:,1].argsort()]

In [16]:
np.savetxt("ruhaha.csv", my_data, delimiter=",")

In [17]:
my_data

array([[1.4610e+03, 3.6700e+02, 6.0620e+03, ..., 5.1200e+00, 2.2016e+00,
        2.0000e+00],
       [8.8500e+02, 3.6700e+02, 5.8020e+03, ..., 5.5200e+00, 2.3736e+00,
        4.0000e+00],
       [2.3600e+02, 3.6700e+02, 5.8020e+03, ..., 5.4300e+00, 1.6833e+00,
        3.0000e+00],
       ...,
       [1.2480e+03, 1.0650e+03, 6.1140e+03, ..., 1.3320e+01, 4.7952e+00,
        4.0000e+00],
       [9.5400e+02, 1.0650e+03, 3.0210e+03, ..., 5.2200e+00, 1.9836e+00,
        3.0000e+00],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan]])

In [19]:
my_data[:,1]

array([ 367.,  367.,  367., ..., 1065., 1065.,   nan])