In [129]:
import numpy as np

In [130]:
my_data = np.genfromtxt('final.csv', delimiter=',')

In [131]:

my_data = my_data[1:]
print(my_data)

[[3.3700e+02 3.7100e+02 6.2800e+03 ... 1.5000e+00 5.1000e-01 2.0000e+00]
 [1.5120e+03 3.7100e+02 6.2800e+03 ... 1.6200e+00 6.3180e-01 3.0000e+00]
 [9.6300e+02 3.7100e+02 4.0180e+03 ... 2.4000e+00 7.2000e-01 1.0000e+00]
 ...
 [2.4000e+01 1.0880e+03 6.4260e+03 ... 6.9200e+00 2.2836e+00 4.0000e+00]
 [9.0600e+02 1.0880e+03 6.4260e+03 ... 2.5200e+00 9.5760e-01 4.0000e+00]
 [9.6200e+02 1.0880e+03 6.4260e+03 ... 5.6100e+00 2.5245e+00 3.0000e+00]]


In [132]:
np.savetxt("ruhaha.csv", my_data, delimiter=",")

In [133]:
my_data = my_data[my_data[:,1].argsort()]

In [134]:
np.savetxt("ruhaha.csv", my_data, delimiter=",")

In [135]:
my_data

array([[1.4830e+03, 3.6700e+02, 2.2000e+03, ..., 4.2600e+00, 1.4058e+00,
        2.0000e+00],
       [1.4350e+03, 3.6700e+02, 8.8300e+03, ..., 2.7200e+00, 1.0880e+00,
        1.0000e+00],
       [7.8500e+02, 3.6700e+02, 8.8300e+03, ..., 4.5600e+00, 1.6872e+00,
        2.0000e+00],
       ...,
       [1.1900e+02, 1.0950e+03, 1.6480e+03, ..., 4.5600e+00, 1.6872e+00,
        2.0000e+00],
       [4.2300e+02, 1.0950e+03, 1.5470e+03, ..., 5.8800e+00, 1.9992e+00,
        4.0000e+00],
       [3.0100e+02, 1.0950e+03, 7.8870e+03, ..., 1.0600e+00, 4.3460e-01,
        2.0000e+00]])

In [136]:
my_data[:,1]

array([ 367.,  367.,  367., ..., 1095., 1095., 1095.])

In [137]:
# month = {}

In [138]:
start = my_data[:,1][0]
# month[start] = 0
count = 0

week = {i:(i-start)//7 for i in my_data[:,1]}

In [139]:
week

{367.0: -0.0,
 368.0: 0.0,
 369.0: 0.0,
 370.0: 0.0,
 371.0: 0.0,
 372.0: 0.0,
 373.0: 0.0,
 374.0: 1.0,
 375.0: 1.0,
 376.0: 1.0,
 377.0: 1.0,
 378.0: 1.0,
 379.0: 1.0,
 380.0: 1.0,
 381.0: 2.0,
 382.0: 2.0,
 383.0: 2.0,
 384.0: 2.0,
 385.0: 2.0,
 386.0: 2.0,
 387.0: 2.0,
 389.0: 3.0,
 390.0: 3.0,
 391.0: 3.0,
 392.0: 3.0,
 393.0: 3.0,
 394.0: 3.0,
 395.0: 4.0,
 398.0: 4.0,
 399.0: 4.0,
 400.0: 4.0,
 401.0: 4.0,
 402.0: 5.0,
 404.0: 5.0,
 405.0: 5.0,
 407.0: 5.0,
 408.0: 5.0,
 409.0: 6.0,
 410.0: 6.0,
 411.0: 6.0,
 412.0: 6.0,
 413.0: 6.0,
 414.0: 6.0,
 415.0: 6.0,
 416.0: 7.0,
 417.0: 7.0,
 418.0: 7.0,
 419.0: 7.0,
 420.0: 7.0,
 421.0: 7.0,
 422.0: 7.0,
 423.0: 8.0,
 424.0: 8.0,
 426.0: 8.0,
 427.0: 8.0,
 428.0: 8.0,
 429.0: 8.0,
 430.0: 9.0,
 431.0: 9.0,
 432.0: 9.0,
 433.0: 9.0,
 434.0: 9.0,
 435.0: 9.0,
 436.0: 9.0,
 437.0: 10.0,
 438.0: 10.0,
 439.0: 10.0,
 440.0: 10.0,
 441.0: 10.0,
 442.0: 10.0,
 443.0: 10.0,
 444.0: 11.0,
 445.0: 11.0,
 446.0: 11.0,
 447.0: 11.0,
 448.0: 11.0,

In [140]:
mod_data = my_data

In [141]:
 mod_data[:,1] = np.array([month[str(int(x))] for x in mod_data[:,1]])

mod_data

In [142]:
mod_data 

array([[1.4830e+03, 0.0000e+00, 2.2000e+03, ..., 4.2600e+00, 1.4058e+00,
        2.0000e+00],
       [1.4350e+03, 0.0000e+00, 8.8300e+03, ..., 2.7200e+00, 1.0880e+00,
        1.0000e+00],
       [7.8500e+02, 0.0000e+00, 8.8300e+03, ..., 4.5600e+00, 1.6872e+00,
        2.0000e+00],
       ...,
       [1.1900e+02, 1.0400e+02, 1.6480e+03, ..., 4.5600e+00, 1.6872e+00,
        2.0000e+00],
       [4.2300e+02, 1.0400e+02, 1.5470e+03, ..., 5.8800e+00, 1.9992e+00,
        4.0000e+00],
       [3.0100e+02, 1.0400e+02, 7.8870e+03, ..., 1.0600e+00, 4.3460e-01,
        2.0000e+00]])

In [166]:
products = [product for product in set(mod_data[:,0])]

# for product in products:
#     x = []
#     for i in my_data:
#         if i[0] = product: 
#             x = [i[1:]]
        

In [172]:
n_week = max([w for w in week])
print(n_week)

n_prod = len(products)
print(n_prod)

print(len(mod_data[0]))

n_feat = len(mod_data[0]) - 2

1095.0
1559
8


In [186]:
features = np.zeros((int(n_prod), int(n_week), int(n_feat)))

print(list(features.shape))

for r in mod_data:
#     print(r[0])
#     print(r[1])
#     print(r[2:])
    features[int(r[0])-1, int(r[1])] = r[2:]
    
print(features.shape)
print(features[0])
print(features[0,0])
print(features[0,0,0])

[1559, 1095, 6]
(1559, 1095, 6)
[[4.7280e+03 5.0100e+02 7.0000e+00 1.1400e+01 3.9900e+00 4.0000e+00]
 [9.7880e+03 0.0000e+00 1.3000e+01 8.5500e+00 4.0185e+00 3.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]]
[4.728e+03 5.010e+02 7.000e+00 1.140e+01 3.990e+00 4.000e+00]
4728.0


In [165]:
np.ndarray(3)

array([ 0.00000000e+00, -2.31584192e+77,  2.31584192e+77])

In [157]:
import random
random.uniform(0,1)

n_week = 213312#sthsth
n_test = 0.2 * n_week
n_train = 0.8 * n_week

train_idx = []

for i in range(n_week):
    
    if len(train_idx) >= n_train:
        train_idx.append(i)
        continue
    
    if len(test_idx) >= n_test:
        test_idx.append(i)
        continue
    
    if rand.uniform(0,1) < 0.8:
        train_idx.append(i)
    else:
        test_idx.append(i)
        



0.9054271510535266